spring.application.name=Turf-Owner

server.port=9001
server.servlet.context-path=/turf

#database config 
spring.datasource.url= jdbc:mysql://localhost:3306/
spring.datasource.username=root
spring.datasource.password=abi26
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create 
