spring.application.name=Turf-User

server.port=9000
server.servlet.context-path=/turf

#database config 
spring.datasource.url= jdbc:mysql://localhost:3306/turfuser
spring.datasource.username=root
spring.datasource.password=abi26
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create 


#jwt validate
jwt.secret=secretabcd1243awdSECRETabcd1243awdSECRET

#spring.security.oauth2.resourceserver.jwt.secret-key=secretabcd1243awdSECRETabcd1243awdSECRET